from dotenv import load_dotenv
import os

load_dotenv()

SUI_CONFIG_PATH = os.getenv("SUI_CONFIG_PATH")
OPEN_AI_API_KEY = os.getenv("OPEN_AI_API_KEY")
SERPER_API_KEY = os.getenv("SERPER_API_KEY")

ORACLE_PACKAGE_ID = os.getenv("ORACLE_PACKAGE_ID")

PROMPTS_OBJECT_ID = os.getenv("PROMPTS_OBJECT_ID")
RESPONSES_OBJECT_ID = os.getenv("RESPONSES_OBJECT_ID")

FUNCTION_CALLS_OBJECT_ID = os.getenv("FUNCTION_CALLS_OBJECT_ID")
FUNCTION_RESPONSES_OBJECT_ID = os.getenv("FUNCTION_RESPONSES_OBJECT_ID")

VECTOR_SEARCH_OBJECT_ID = os.getenv("VECTOR_SEARCH_OBJECT_ID")
VECTOR_SEARCH_RESPONSES_OBJECT_ID = os.getenv("VECTOR_SEARCH_RESPONSES_OBJECT_ID")

PRIVATE_KEY = os.getenv("PRIVATE_KEY")
RPC_URL = os.getenv("RPC_URL")
REGISTRY_PACKAGE_ID = os.getenv("REGISTRY_PACKAGE_ID")
REGISTRY_OBJECT_ID = os.getenv("REGISTRY_OBJECT_ID")
ADMIN_CAP_OBJECT_ID = os.getenv("ADMIN_CAP_OBJECT_ID")
